In [6]:
import pandas as pd
df = pd.read_parquet('~/tmp/sparkdata')
df.to_parquet('~/tmp/sparkpartition', partition_cols=['load_dt','multiMovieYn', 'repNationCd'])

In [10]:
df

,rnum,rank,rankInten,rankOldAndNew,movieCd,movieNm,openDt,salesAmt,salesShare,salesInten,...,salesAcc,audiCnt,audiInten,audiChange,audiAcc,scrnCnt,showCnt,load_dt,multiMovieYn,repNationCd
0,1,1,0,OLD,20137048,국제시장,2014-12-17,6129982500,47.3,2797599300,...,47219550096,751754,275212,57.8,6097431,941,4650,20150101,N,NaN
1,2,2,1,OLD,20143642,테이큰 3,2015-01-01,2644551100,20.4,1640018100,...,3658460100,321653,177118,122.5,467280,614,2947,20150101,N,NaN
2,3,3,-1,OLD,20149859,마다가스카의 펭귄,2014-12-31,1687516200,13.0,672528400,...,2736013000,212779,67641,46.6,361669,594,1846,20150101,N,NaN
3,4,4,0,OLD,20149265,기술자들,2014-12-24,1299883700,10.0,350703100,...,14952363848,160371,22538,16.4,1938454,464,1886,20150101,N,NaN
4,5,5,0,OLD,20140226,호빗: 다섯 군대 전투,2014-12-17,609678800,4.7,167361700,...,22038162144,69988,8214,13.3,2579875,346,825,20150101,N,NaN
5,6,6,0,OLD,20147176,상의원,2014-12-24,230484800,1.8,24817000,...,5524209364,28439,-1473,-4.9,705071,258,491,20150101,N,NaN
6,7,7,0,OLD,20149120,인터스텔라,2014-11-06,192143100,1.5,70045000,...,80863567400,20636,5353,35,10125883,97,175,20150101,N,NaN
7,8,8,1,OLD,20143602,일곱난쟁이,2014-12-24,65447200,0.5,8734100,...,1383364100,9045,749,9,193706,90,134,20150101,N,NaN
8,9,9,-1,OLD,20143422,숲속으로,2014-12-24,55772600,0.4,-12642300,...,2465335488,7195,-2604,-26.6,324601,113,154,20150101,N,NaN
9,10,10,0,OLD,20143639,뽀로로 극장판 눈요정 마을 대모험,,27846600,0.2,11699700,...,1188395900,5561,2333,72.3,237436,66,83,20150101,N,NaN
10,1,1,0,OLD,20141111,"님아, 그 강을 건너지 마오",2014-11-27,1479015600,68.2,698744500,...,31324845079,178941,64938,57,4025319,473,1979,20150101,Y,NaN
11,2,2,1,OLD,20130574,개를 훔치는 완벽한 방법,2014-12-31,299346400,13.8,118500500,...,608002300,37741,10759,39.9,80633,196,650,20150101,Y,NaN
12,3,3,-1,OLD,20143344,눈의 여왕 2: 트롤의 마법거울,2014-12-24,233190700,10.7,43780000,...,3856612400,30978,3375,12.2,529298,246,415,20150101,Y,NaN
13,4,4,0,OLD,20141614,더 테너 리리코 스핀토,2014-12-31,69620500,3.2,24180800,...,200984700,8446,1821,27.5,26316,169,367,20150101,Y,NaN
14,5,5,19,OLD,20143045,내일을 위한 시간,2015-01-01,26098700,1.2,25508700,...,50568800,3035,2955,3693.8,6034,39,89,20150101,Y,NaN
15,6,6,-1,OLD,20141621,마미,2014-12-18,13704500,0.6,-857000,...,288455700,1533,-587,-27.7,36655,32,47,20150101,Y,NaN
16,7,7,-1,OLD,20143343,무드 인디고,2014-12-11,10800500,0.5,1382500,...,276643700,1232,-104,-7.8,34616,26,44,20150101,Y,NaN
17,8,8,0,OLD,20143081,그 사람 그 사랑 그 세상,2014-11-20,9467000,0.4,489000,...,162552500,1202,69,6.1,22070,7,14,20150101,Y,NaN
18,9,9,-2,OLD,20142964,클라우즈 오브 실스마리아,2014-12-18,9570000,0.4,227500,...,181004299,1123,-189,-14.4,22730,20,25,20150101,Y,NaN
19,10,10,-1,OLD,20129490,산,,1533000,0.1,75000,...,5523000,761,32,4.4,2746,1,4,20150101,Y,NaN
20,1,1,1,OLD,20143642,테이큰 3,2015-01-01,2644551100,47.4,1640018100,...,3658460100,321653,177118,122.5,467280,614,2947,20150101,NaN,F
21,2,2,-1,OLD,20149859,마다가스카의 펭귄,2014-12-31,1687516200,30.3,672528400,...,2736013000,212779,67641,46.6,361669,594,1846,20150101,NaN,F
22,3,3,0,OLD,20140226,호빗: 다섯 군대 전투,2014-12-17,609678800,10.9,167361700,...,22038162144,69988,8214,13.3,2579875,346,825,20150101,NaN,F
23,4,4,0,OLD,20143344,눈의 여왕 2: 트롤의 마법거울,2014-12-24,233190700,4.2,43780000,...,3856612400,30978,3375,12.2,529298,246,415,20150101,NaN,F
24,5,5,0,OLD,20149120,인터스텔라,2014-11-06,192143100,3.4,70045000,...,80863567400,20636,5353,35,10125883,97,175,20150101,NaN,F
25,6,6,1,OLD,20143602,일곱난쟁이,2014-12-24,65447200,1.2,8734100,...,1383364100,9045,749,9,193706,90,134,20150101,NaN,F
26,7,7,-1,OLD,20143422,숲속으로,2014-12-24,55772600,1.0,-12642300,...,2465335488,7195,-2604,-26.6,324601,113,154,20150101,NaN,F
27,8,8,19,OLD,20143045,내일을 위한 시간,2015-01-01,26098700,0.5,25508700,...,50568800,3035,2955,3693.8,6034,39,89,20150101,NaN,F
28,9,9,-1,OLD,20141621,마미,2014-12-18,13704500,0.2,-857000,...,288455700,1533,-587,-27.7,36655,32,47,20150101,NaN,F
29,10,10,-1,OLD,20143343,무드 인디고,2014-12-11,10800500,0.2,1382500,...,276643700,1232,-104,-7.8,34616,26,44,20150101,NaN,F
30,1,1,0,OLD,20137048,국제시장,2014-12-17,6129982500,64.1,2797599300,...,47219550096,751754,275212,57.8,6097431,941,4650,20150101,NaN,K
31,2,2,1,OLD,20141111,"님아, 그 강을 건너지 마오",2014-11-27,1479015600,15.5,698744500,...,31324845079,178941,64938,57,4025319,473,1979,20150101,NaN,K
32,3,3,-1,OLD,20149265,기술자들,2014-12-24,1299883700,13.6,350703100,...,14952363848,160371,22538,16.4,1938454,464,1886,20150101,NaN,K
33,4,4,1,OLD,20130574,개를 훔치는 완벽한 방법,2014-12-31,299346400,3.1,118500500,...,608002300,37741,10759,39.9,80633,196,650,20150101,NaN,K
34,5,5,-1,OLD,20147176,상의원,2014-12-24,230484800,2.4,24817000,...,5524209364,28439,-1473,-4.9,705071,258,491,20150101,NaN,K
35,6,6,0,OLD,20141614,더 테너 리리코 스핀토,2014-12-31,69620500,0.7,24180800,...,200984700,8446,1821,27.5,26316,169,367,20150101,NaN,K
36,7,7,0,OLD,20143639,뽀로로 극장판 눈요정 마을 대모험,,27846600,0.3,11699700,...,1188395900,5561,2333,72.3,237436,66,83,20150101,NaN,K
37,8,8,2,OLD,20143081,그 사람 그 사랑 그 세상,2014-11-20,9467000,0.1,489000,...,162552500,1202,69,6.1,22070,7,14,20150101,NaN,K
38,9,9,2,OLD,20141114,쿼바디스,2014-12-10,4046900,0.0,1585400,...,117029800,509,114,28.9,15399,12,19,20150101,NaN,K
39,10,10,0,NEW,19900042,장군의 아들,1990-06-09,416000,0.0,416000,...,1446000,208,208,100,723,1,4,20150101,NaN,K